# Generated by Django 3.2.4 on 2021-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='conteudo',
            field=models.TextField(max_length=300),
        ),
    ]
